<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Carrinho' => $baseDir . '/model/Carrinho.class.php',
    'Clientes' => $baseDir . '/model/Clientes.class.php',
    'Config' => $baseDir . '/model/Config.class.php',
    'Pedidos' => $baseDir . '/model/Pedidos.class.php',
    'Produtos' => $baseDir . '/model/Produtos.class.php',
    'Rotas' => $baseDir . '/model/Rotas.class.php',
    'Template' => $baseDir . '/model/Template.class.php',
);
