<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit7c051f2d6435339b09dbc2832348953f
{
    public static $files = array (
        'f084d01b0a599f67676cffef638aa95b' => __DIR__ . '/..' . '/smarty/smarty/libs/bootstrap.php',
    );

    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static $classMap = array (
        'Carrinho' => __DIR__ . '/../..' . '/model/Carrinho.class.php',
        'Clientes' => __DIR__ . '/../..' . '/model/Clientes.class.php',
        'Config' => __DIR__ . '/../..' . '/model/Config.class.php',
        'Pedidos' => __DIR__ . '/../..' . '/model/Pedidos.class.php',
        'Produtos' => __DIR__ . '/../..' . '/model/Produtos.class.php',
        'Rotas' => __DIR__ . '/../..' . '/model/Rotas.class.php',
        'Template' => __DIR__ . '/../..' . '/model/Template.class.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit7c051f2d6435339b09dbc2832348953f::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit7c051f2d6435339b09dbc2832348953f::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit7c051f2d6435339b09dbc2832348953f::$classMap;

        }, null, ClassLoader::class);
    }
}
